# github-data-collector configuration

collectors:
  contributions:
    enabled: true
    sinceDate: "2024-01-01"  # Fetch all contributions since this date

  releases:
    enabled: true
    sinceDate: "2024-01-01"  # Fetch all releases since this date

  recentWork:
    enabled: true
    apiLimit: 10

  stars:
    enabled: true

  rss:
    enabled: false

paths:
  template: templates/README.md.liquid
  output: README.md
  data: data
